### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by sunil-samuel** [puemos/hls-downloader-chrome-extension#18]
I see the download link (very low visible) but when I click on it, nothing happens.

**Comment by fengshuo2004** [comment]
The same is happening to me. As a programmer myself I feel like those thing might have happened behind the scene:
- Did the client failed to communicate with the m3u8 file host? (I feel this is unlikely because I watched the percentage going all the way up to 100% in about 3 minutes so it must have downloaded something);
- Or my computer failed to communicate with your backend download server;
- There is a fault in the chrome extension itself?

By the way the button we clicked is the one under "download" menu, right side by the URL, a monitor with a downward arrow on it.

Another few things to notice:
- For the file I was trying to download, a non-chrome-extension m3u8 downloader would not work, and the server responds `403 forbidden`. I think this might be because of header or cookie authentication problem.
- Before I used this chrome extension I manuelly located the m3u8 file in the webpage using the network panel of developer tools, that URL is exactly the same as what the sniffer of this extension gave me, which shows **the sniffer is working correctly**.
- The m3u8 file points to about 40x `.ts` files using full URL, each `.ts` files lasts 10 seconds. Those `.ts` files can be downloaded seperately and opened, but it would be pratically impossible to manually download and stitch all 40 `.ts` files together

**Comment by puemos** [comment]
Hey @fengshuo200, thanks for this awesome comment.
I will try to find out what is going on and hopefully will release a fix.
Thanks 😊

**Comment by BazzaBlogz** [comment]
I have this as well. The download button just doesn't open the save option.

**Comment by own3mall** [comment]
I also have this problem from time to time.  When I click on the Download icon, nothing happens.  If I clear my cache, close Chrome, open Chrome, clear my cache again, revisit the same video, go through the HLS sniffer process, and choose the bitrate I want to download, it usually works.  However, it happens a lot where it just doesn't do anything.  Clearing cache and trying again seems to get it to work sometimes.  

Any luck tracking this down?

**Comment by puemos** [comment]
I think I solved it on v1.6.3
You will have to wait until google will approve the release, please let me know if it solves your issues.

**Comment by vinnie333** [comment]
Any rough ETA when google will allow v1.6.3  ....?  Currently on 1.20 from Chrome Store ...??
Is there a way to update it ?

**Comment by KarunaGovind** [comment]
Sorry to re-open an old thread, but forbidden issue has shown up again. This is what I get in the console:

``
TypeError: Cannot read properties of undefined (reading 'moov')    at getAllTrackStatus (chrome-extension://iogidnfllpdhagebkblkgbfijkbkjdmm/js/loader.js:965:92)    at async _buildMP4 (chrome-extension://iogidnfllpdhagebkblkgbfijkbkjdmm/js/loader.js:1111:26)    at async flush (chrome-extension://iogidnfllpdhagebkblkgbfijkbkjdmm/js/loader.js:2646:18)    at async internalUIMessage (chrome-extension://iogidnfllpdhagebkblkgbfijkbkjdmm/js/loader.js:3844:33)    at async HTMLAnchorElement.saveRequest (chrome-extension://iogidnfllpdhagebkblkgbfijkbkjdmm/js/loader.js:3919:7)
``

Which then results in `https://www.hlsloader.com/null` being downloaded (hence the 403).

Any ideas?
